### ISSUE TITLE
Can't use the module anymore

### ISSUE THREAD

**Issue by Freezor** [geoidesic/foundryvtt-actor-studio#112]
I don't know what exactly happend, but when I open the actor Studio for a new Character I only see white content.

In the console I get this error:
`Uncaught (in promise) TypeError: undefined. Failed to fetch dynamically imported module: https://foundry.friesenheim.duckdns.org/modules/foundryvtt-actor-studio/dist/Class-CNC9oi-F.js`

[Detected 1 package: foundryvtt-actor-studio(1.5.6)]
  | Promise.then (async) |   |  
-- | -- | -- | --
  | $$self.$$.update | @ | Tabs.svelte:20
  | init | @ | Component.js:144
  | Tabs | @ | Tabs.svelte:14
  | create_default_slot$2 | @ | PCAppShell.svelte:78
  | create_slot | @ | utils.js:165
  | create_else_block$5 | @ | ResizableHandle.svelte:25
  | create_fragment$h | @ | ApplicationShell.svelte:360
  | init | @ | Component.js:148
  | ApplicationShell | @ | ApplicationShell.svelte:157
  | create_fragment$9 | @ | PCAppShell.svelte:78
  | init | @ | Component.js:148
  | PCAppShell | @ | PCAppShell.svelte:24
  | loadSvelteConfig | @ | loadSvelteConfig.js:91
  | _injectHTML | @ | SvelteApplication.js:507
  | renderPatch | @ | application-render.js:55
  | await in renderPatch (async) |   |  
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:614
  | 🎁Application.prototype._render#0 | @ | libWrapper-wrapper.js:193
  | _render | @ | SvelteApplication.js:886
  | render | @ | foundry.js:5793
  | render | @ | PCApplication.js:114
  | handleButtonClick | @ | index.js:282
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

**Comment by geoidesic** [comment]
1. What version of Actor Studio? 
2. Did you try clear your browser cache?

I just tested the later version and it seems ok.

**Comment by geoidesic** [comment]
Hi again. I found the issue. v1.5.6 was broken during the build phase.
Fixed in v1.5.7.
Tx for the bug report!

**Comment by Freezor** [comment]
That resolved the previous issue, but now I'm encountering a new problem: I cannot add any attribute points unless I use the manual entry method.

### Console Errors

Here are the console errors I’m receiving:

1. **TypeError**: 
   ```
   Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'value')
   [Detected 1 package: foundryvtt-actor-studio (1.5.7)]
       at Array.updateValue (StandardArray.svelte:39:69)
       at index.js:121:61
   ```

2. **CharacterData Validation Error**:
   ```
   foundry-esm.js:4710 Uncaught Error: undefined. CharacterData validation errors:
   abilities: [object Object]
   [Detected 2 packages: system:dnd5e (4.0.4), foundryvtt-actor-studio (1.5.7)]
       at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
       at CharacterData.validate (foundry-esm.js:10432:61)
       at CharacterData.validate (abstract.mjs:208:18)
       at new DataModel (foundry-esm.js:10181:12)
       at new TypeDataModel (foundry-esm.js:10796:7)
       at new SystemDataModel (abstract.mjs:20:16)
       at new ActorDataModel (abstract.mjs:341:8)
       at new Base (abstract.mjs:294:18)
       at new CommonTemplate (common.mjs:26:16)
       at new CreatureTemplate (creature.mjs:26:16)
       at new CharacterData (character.mjs:69:16)
       at TypeDataField.initialize (foundry-esm.js:9796:26)
       at Actor5e._initialize (foundry-esm.js:10340:29)
       at Actor5e._initialize (foundry-esm.js:11020:13)
       at Actor5e._initialize (foundry.js:10628:13)
       at Actor5e.updateSource (foundry-esm.js:10520:35)
       at Array.updateValue (PointBuy.svelte:19:10)
       at index.js:121:61
   ```

**Comment by geoidesic** [comment]
I'm not able to replicate this problem. I've installed v1.5.7 on a remote server and all the various attribute selection methods are working fine.

Can you please try:
1. Clear your browse cache
2. Try create a new Actor using actor studio
3. Take a screenshot and paste it here
4. Also show the errors from the other attribute entry types – you've only shown the error for StandardArray, they will each be different.

Looking at the error message you're getting – it doesn't really make sense. It is suggesting that the character's data is corrupted – i.e. the character does not have attribute data, which should not be possible.

**Comment by geoidesic** [comment]
@Freezor 

There aren't any currently known conflicts with other modules but it's possible.

You can eliminate conflicts by disabling all your other modules and just having Actor Studio enabled. To do this safely, use `Forien's Copy Environment` `Find the Culprit` and / or `Module Profiles` modules.

I don't know anything about German Language settings. But again you can test this by turning them off. 

Which version of FoundryVTT and dnd5e system are you using? 
I've been testing on FoundryVTT v12 stable build 331 and dnd5e v4.0.4

**Comment by geoidesic** [comment]
Any luck?

**Comment by noobishfish** [comment]
I've same bug. Problem was solved with using English.

Log of error:
![image](https://github.com/user-attachments/assets/e7d521ba-ee13-4072-994e-8ab3a48b0f81)

**Comment by geoidesic** [comment]
> I've same bug. Problem was solved with using English.

Can you give me steps to replicate this bug?

**Comment by noobishfish** [comment]
Huh. Yes, i think:
1) Install Ru-eng module: https://github.com/phenomen/foundry-vtt-ru
2) Start game world
3) Activate Russian Translation module
4) In game settings change prefered language on Russian
5) Try to create new Actor with Actor Studio
6) Pick a point buy
7) Try to incremet some stat with button
8) Get an error

**Comment by Freezor** [comment]
I finally got time to revisit that issue in a new world setup and encountered a new error:  

```
StandardArray.svelte:40 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')  
[Detected 1 package: foundryvtt-actor-studio(1.6.4)]  
    at Array.updateValue (StandardArray.svelte:40:69)  
    at index.js:121:61  
```

Additionally, this error appears:  

```
foundry-esm.js:4710 Uncaught (in promise) Error: CharacterData validation errors:  
  abilities:   
    Kon:   
      value: must be an integer  
[Detected 2 packages: system:dnd5e(4.3.3), foundryvtt-actor-studio(1.6.4)]  
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)  
    at CharacterData.validate (foundry-esm.js:10432:61)  
    at CharacterData.validate (abstract.mjs:209:18)  
    at new DataModel (foundry-esm.js:10181:12)  
    at new TypeDataModel (foundry-esm.js:10796:7)  
    at new SystemDataModel (abstract.mjs:21:16)  
    at new ActorDataModel (abstract.mjs:342:8)  
    at new Base (abstract.mjs:295:18)  
    at new CommonTemplate (common.mjs:29:16)  
    at new CreatureTemplate (creature.mjs:27:16)  
    at new CharacterData (character.mjs:76:16)  
    at TypeDataField.initialize (foundry-esm.js:9796:26)  
    at Actor5e._initialize (foundry-esm.js:10340:29)  
    at Actor5e.updateSource (foundry-esm.js:10520:35)  
    at Array.roll (Roll.svelte:33:10)  
```

**Active Modules and Versions:**  
- **D&D 5e:** 4.3.3  
- **ActorStudio:** 1.6.4  
- **Additional Metric Ruler Labels:** 3.3.1  
- **Babele:** 2.6.1  
- **Custom D&D5e:** 1.3.4  
- **DnD5e German Translation:** 4.1.1  
- **German [Core]:** 12.0  
- **libWrapper:** 1.13.2.0  
- **TheRipper93's Module Hub:** 4.1.3  
- **Tidy 5e Sheets:** 9.1.0  


### **And I found out what caused the issue**

It is the german translation. somehow that breaks the attribute value selection.

**Comment by geoidesic** [comment]
Well that correlates with what @noobishfish said above. A different module breaks his setup but it's also a translation module. When I find time I will have a look and see if I can fix this. If you'd like it to be prioritised, please consider a donation via my [Github sponsors link](https://github.com/sponsors/geoidesic).

**Comment by geoidesic** [comment]
@Freezor is this still an issue for German in v1.8.11? 
I installed the German language core model and it seems to work. 
I also tried it with Russian and there I can see the error.

**Comment by geoidesic** [comment]
fixed in release 1.8.12

**Comment by geoidesic** [comment]
@Freezor @noobishfish perhaps you'd be interested in joining the [Discord Server](https://discord.gg/sQgVnSGRUj). I'd be happy to set up channels for Russian and German discussion of the module there – if you have friends who would like to join and discuss the module in their native language. Just a thought!

**Comment by Freezor** [comment]
Hey. Now it works again. many thanks
