### ISSUE TITLE
After level up, AS application can't close

### ISSUE THREAD

**Issue by geoidesic** [geoidesic/foundryvtt-actor-studio#65]
```
Error: Error thrown in hooked function '' for hook 'gas.close'. Cannot read properties of undefined (reading 'render')
    at Hooks.onError (foundry.js:630:24)
    at #call (foundry.js:612:36)
    at Hooks.call (foundry.js:590:38)
    at Object.fn (index.js:143:11)Caused by: TypeError: Cannot read properties of undefined (reading 'render')
    at Object.fn (PCAppShell.svelte:57:24)
    at #call (foundry.js:608:20)
    at Hooks.call (foundry.js:590:38)
    at Object.fn (index.js:143:11)
```

**Comment by geoidesic** [comment]
fixed in 1.1.1
